baseURL = "https://sainswor.github.io/"
languageCode = "en-us"
title = "From Draenor With Love"
theme = "cloning-vat"
relativeURLs = true

[markup.goldmark.renderer]
    unsafe= true

[params]
    backgroundPath = "/images/fdwl-background.jpg"
