baseURL = "https://fromdraenor.ca/"
languageCode = "en-us"
title = "From Draenor With Love"
theme = "cloning-vat"
relativeURLs = true

[markup.goldmark.renderer]
    unsafe= true

[params]
    backgroundPath = "/images/fdwl-background.jpg"

[params.staticman]
    endpoint = "https://fdwl-comments.herokuapp.com/v2/entry"
    username = "sainswor"
    repository = "sainswor.github.io"
    branch = "master"
    
[taxonomies]
    chapter = 'chapters'